### ISSUE TITLE
'YTHeaders/YTPlayerViewController.h' file not found

### ISSUE THREAD

**Issue by Cregin** [therealFoxster/DontEatMyContent#40]
==> Preprocessing src/Tweak.x…
In file included from src/Settings.x:1:
/Users/runner/work/uYouEnhanced/uYouEnhanced/main/Tweaks/**DontEatMyContent**/src/Tweak.h:4:9: fatal error: 'YTHeaders/YTPlayerViewController.h' file not found
#import <YTHeaders/YTPlayerViewController.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/Users/runner/work/uYouEnhanced/uYouEnhanced/theos/makefiles/instance/rules.mk:392: /Users/runner/work/uYouEnhanced/uYouEnhanced/main/.theos/obj/arm64/src/Settings.x.bbc9a278.o] Error 1
==> Compiling src/Settings.x (arm64)…
make[4]: *** Waiting for unfinished jobs....
In file included from src/Tweak.x:1:
==> Compiling src/Tweak.x (arm64)…
/Users/runner/work/uYouEnhanced/uYouEnhanced/main/Tweaks/**DontEatMyContent**/src/Tweak.h:4:9: fatal error: 'YTHeaders/YTPlayerViewController.h' file not found
#import <YTHeaders/YTPlayerViewController.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[4]: *** [/Users/runner/work/uYouEnhanced/uYouEnhanced/theos/makefiles/instance/rules.mk:392:

**Comment by therealFoxster** [comment]
Should be fixed in 9236511

**Comment by Cregin** [comment]
![image](https://github.com/user-attachments/assets/ba338c03-1ab8-4ffd-ab0c-2e74e4de273e)
Still reporting the same error, uYouEnhanced did not synchronize this change

**Comment by mustafacakirogludev** [comment]
I am still having this issue:
![{6132335E-6D93-4907-95C5-2E7336A34060}](https://github.com/user-attachments/assets/0b736b7a-8237-436a-a78d-bf591c78fefc)
any ideas @therealFoxster ?

**Comment by therealFoxster** [comment]
Is that uYouPlus? If it's something else then I'm not sure

**Comment by mustafacakirogludev** [comment]
> Is that uYouPlus? If it's something else then I'm not sure

Ah sorry I didn't think the image would be misleading. I was just modifying a github action to build and inject your tweak for my own personal use as I don't have access to a PC right now. 

In summary action itself is irrelevant, I am just using it to run commands. I tried following and got the same error as the OP:

`make clean package DEBUG=0 FINALPACKAGE=1 `

`make package FINALPACKAGE=1`
          
`make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless`

**Comment by therealFoxster** [comment]
I see. The only thing I can think of is that when you're cloning the repo make sure you're doing so recursively so that the submodules are cloned as well, but otherwise I'm not sure cause I haven't heard similar issues reported

**Comment by mustafacakirogludev** [comment]
> The only thing I can think of is that when you're cloning the repo make sure you're doing so recursively so that the submodules are cloned as well

That was spot on, thanks!! If anyone else wanders into this thread with the same problem, you can just add `--recurse-submodules` to your git commit and that's it.
